### ISSUE TITLE
Pangolin/pangolearn failed, data column mismatch? 

### ISSUE THREAD

**Issue by biocyberman** [cov-lineages/pangolin#100]
Hi @aineniamh 
I don't understand the error, could you help

```
pangolin pangolin -pv
pangoLEARN 2020-08-29_3
pangolin -lv
lineages 2020-05-19
pangolin -v
pangolin 2.0.8
python --version
Python 3.6.10
```

```
Looking in /home/bin/opt/mc3/envs/pangolin/lib/python3.6/site-packages/pangoLEARN/data for data files...

Data files found
Trained model:  /home/bin/opt/mc3/envs/pangolin/lib/python3.6/site-packages/pangoLEARN/data/decisionTree_v1.joblib
Header file:    /home/bin/opt/mc3/envs/pangolin/lib/python3.6/site-packages/pangoLEARN/data/decisionTreeHeaders_v1.joblib
Lineages csv:   /home/bin/opt/mc3/envs/pangolin/lib/python3.6/site-packages/pangoLEARN/data/lineages.metadata.csv
Job counts:
        count   jobs
        1       add_failed_seqs
        1       all
        1       datafunk_trim_and_pad
        1       minimap2_check_distance
        1       minimap2_to_reference
        1       pangolearn
        1       parse_paf
        7

        minimap2 -x asm5 /home/bin/opt/mc3/envs/pangolin/lib/python3.6/site-packages/pangolin/data/reference.fasta /ncov-aau/results/Denmark/pangtmp/tmpcojya8l_/query.post_qc.fasta -o /ncov-aau/results/Denmark/pangtmp/tmpcojya8l_/reference_mapped.paf &> /ncov-aau/results/Denmark/pangtmp/tmpcojya8l_/logs/minimap2_check.log

Job counts:
        count   jobs
        1       parse_paf
        1

        minimap2 -a -x asm5 /home/bin/opt/mc3/envs/pangolin/lib/python3.6/site-packages/pangolin/data/reference.fasta /ncov-aau/results/Denmark/pangtmp/tmpcojya8l_/mappable.fasta -o /ncov-aau/results/Denmark/pangtmp/tmpcojya8l_/reference_mapped.sam &> /ncov-aau/results/Denmark/pangtmp/tmpcojya8l_/logs/minimap2_sam.log


        datafunk sam_2_fasta           -s /ncov-aau/results/Denmark/pangtmp/tmpcojya8l_/reference_mapped.sam           -r /home/bin/opt/mc3/envs/pangolin/lib/python3.6/site-packages/pangolin/data/reference.fasta           -o /ncov-aau/results/Denmark/pangtmp/tmpcojya8l_/post_qc_query.aligned.fasta           -t [265:29674]           --pad           --log-inserts


        pangolearn.py --header-file /home/bin/opt/mc3/envs/pangolin/lib/python3.6/site-packages/pangoLEARN/data/decisionTreeHeaders_v1.joblib --model-file /home/bin/opt/mc3/envs/pangolin/lib/python3.6/site-packages/pangoLEARN/data/decisionTree_v1.joblib --reference-file /home/bin/opt/mc3/envs/pangolin/lib/python3.6/site-packages/pangolin/data/reference.fasta --fasta /ncov-aau/results/Denmark/pangtmp/tmpcojya8l_/post_qc_query.aligned.fasta -o /ncov-aau/results/Denmark/pangtmp/tmpcojya8l_/lineage_report.pass_qc.csv

loading model 10/02/2020, 09:09:35
processing block of 1001 sequences 10/02/2020, 09:09:51
Traceback (most recent call last):
  File "/home/bin/opt/mc3/envs/pangolin/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 497, in _list_to_arrays
    content, columns, dtype=dtype, coerce_float=coerce_float
  File "/home/bin/opt/mc3/envs/pangolin/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 581, in _convert_object_array
    f"{len(columns)} columns passed, passed data had "
AssertionError: 15818 columns passed, passed data had 29903 columns

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bin/opt/mc3/envs/pangolin/bin/pangolearn.py", line 125, in <module>
    df = pd.DataFrame(seqList, columns=indiciesToKeep)
  File "/home/bin/opt/mc3/envs/pangolin/lib/python3.6/site-packages/pandas/core/frame.py", line 474, in __init__
    arrays, columns = to_arrays(data, columns, dtype=dtype)
  File "/home/bin/opt/mc3/envs/pangolin/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 461, in to_arrays
    return _list_to_arrays(data, columns, coerce_float=coerce_float, dtype=dtype)
  File "/home/bin/opt/mc3/envs/pangolin/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 500, in _list_to_arrays
    raise ValueError(e) from e
ValueError: 15818 columns passed, passed data had 29903 columns
[Fri Oct  2 09:09:51 2020]
Error in rule pangolearn:
    jobid: 2
    output: /ncov-aau/results/Denmark/pangtmp/tmpcojya8l_/lineage_report.pass_qc.csv
    shell:

        pangolearn.py --header-file /home/bin/opt/mc3/envs/pangolin/lib/python3.6/site-packages/pangoLEARN/data/decisionTreeHeaders_v1.joblib --model-file /home/bin/opt/mc3/envs/pangolin/lib/python3.6/site-packages/pangoLEARN/data/decisionTree_v1.joblib --reference-file /home/bin/opt/mc3/envs/pangolin/lib/python3.6/site-packages/pangolin/data/reference.fasta --fasta /ncov-aau/results/Denmark/pangtmp/tmpcojya8l_/post_qc_query.aligned.fasta -o /ncov-aau/results/Denmark/pangtmp/tmpcojya8l_/lineage_report.pass_qc.csv

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Comment by biocyberman** [comment]
Is it because my input fasta is corrupted? Visual inspection didn't show anything.

**Comment by biocyberman** [comment]
Breaking this line into two steps helped to overcome the error:

https://github.com/cov-lineages/pangolin/blob/master/pangolin/scripts/pangolearn.py#L125

```python
df = pd.DataFrame(seqList)
df = pd.DataFrame(df, columns=indiciesToKeep)
```

Then scikit-learn complains that model has 7091 features, whereas input has 7092 features :-?

**Comment by aineniamh** [comment]
Hi @biocyberman, that's a new one. I've had a chat with @emilyscher and it's got to be something about the input reference being a different length to the reference that the data was trained on. 

If you had an example sequence that's throwing this error- it could be that minimap2 is failing to scaffold the sequence properly or it could be a versioning thing between the reference used in pangoLEARN for the most recent training and the one being run in pangolin. 

I'll have a look into it and hopefully sort that out soon!

**Comment by biocyberman** [comment]
Thanks for taking a look into this @aineniamh  and @emilyscher. Not having looked deeper, I am wondering if line 109 could cause 1 feature difference in model and input? https://github.com/cov-lineages/pangolin/blob/142d62cc916f85e1153ae38dcd479510090978d3/pangolin/scripts/pangolearn.py#L109

For the pandas error. I still don't know why it requires making dataframe before subsetting it. Maybe if `seqList` is already a dataframe, df = seqList.iloc[, indiciesToKeep] would make it more obvious and work as expected?

**Comment by biocyberman** [comment]
This is the trace for the second error:

```
Traceback (most recent call last):
  File "/home/bin/opt/mc3/envs/pangolin/bin/pangolearn.py", line 144, in <module>
    predictions = loaded_model.predict_proba(df)
  File "/home/bin/opt/mc3/envs/pangolin/lib/python3.6/site-packages/sklearn/tree/_classes.py", line 922, in predict_proba
    X = self._validate_X_predict(X, check_input)
  File "/home/bin/opt/mc3/envs/pangolin/lib/python3.6/site-packages/sklearn/tree/_classes.py", line 399, in _validate_X_predict
    % (self.n_features_, n_features))
ValueError: Number of features of the model must match the input. Model n_features is 79091 and input n_features is 79092
[Fri Oct  2 13:59:37 2020]
Error in rule pangolearn:
    jobid: 2
    output: /ncov-aau/results/Denmark/pangtmp/tmpdghjqg3r/lineage_report.pass_qc.csv
    shell:

        pangolearn.py --header-file /home/bin/opt/mc3/envs/pangolin/lib/python3.6/site-packages/pangoLEARN/data/decisionTreeHeaders_v1.joblib --model-file /home/bin/opt/mc3/envs/pangolin/lib/python3.6/site-packages/pangoLEARN/data/decisionTree_v1.joblib --reference-file /home/bin/opt/mc3/envs/pangolin/lib/python3.6/site-packages/pangolin/data/reference.fasta --fasta /ncov-aau/results/Denmark/pangtmp/tmpdghjqg3r/post_qc_query.aligned.fasta -o /ncov-aau/results/Denmark/pangtmp/tmpdghjqg3r/lineage_report.pass_qc.csv

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

**Comment by aineniamh** [comment]
@biocyberman, @benjamincjackson found the issue. 
The reference file was being added unnecessarily to the batched >1000 sequence queries and this was throwing the error!

**Comment by biocyberman** [comment]
@aineniamh Great work. Can imagine it is an elusive bug.

**Comment by biocyberman** [comment]
I confirm the error is gone after I update to the latest commit:

`conda run -n pangolin pip install git+https://github.com/cov-lineages/pangolin.git --upgrade`
