### ISSUE TITLE
scikit-learn

### ISSUE THREAD

**Issue by damientully** [cov-lineages/pangolin#109]
Hi,

I seem to be getting an error since the new update yesterday when trying the test sequences. It's complaining about scikit-learn
```
Traceback (most recent call last):
  File "/Users/damientully/.pyenv/versions/anaconda3-5.3.1/envs/pangolin/lib/python3.6/site-packages/scikit_learn-0.24.0rc1-py3.6-macosx-10.7-x86_64.egg/sklearn/__check_build/__init__.py", line 44, in <module>
    from ._check_build import check_build  # noqa
ImportError: dlopen(/Users/damientully/.pyenv/versions/anaconda3-5.3.1/envs/pangolin/lib/python3.6/site-packages/scikit_learn-0.24.0rc1-py3.6-macosx-10.7-x86_64.egg/sklearn/__check_build/_check_build.cpython-36m-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/damientully/.pyenv/versions/anaconda3-5.3.1/envs/pangolin/lib/python3.6/site-packages/scikit_learn-0.24.0rc1-py3.6-macosx-10.7-x86_64.egg/sklearn/__check_build/../.dylibs/libomp.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/damientully/.pyenv/versions/anaconda3-5.3.1/envs/pangolin/lib/python3.6/site-packages/scikit_learn-0.24.0rc1-py3.6-macosx-10.7-x86_64.egg/sklearn/__check_build/../.dylibs/libomp.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/damientully/.pyenv/versions/anaconda3-5.3.1/envs/pangolin/bin/pangolearn.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
  File "/Users/damientully/.pyenv/versions/anaconda3-5.3.1/envs/pangolin/lib/python3.6/site-packages/scikit_learn-0.24.0rc1-py3.6-macosx-10.7-x86_64.egg/sklearn/__init__.py", line 81, in <module>
    from . import __check_build  # noqa: F401
  File "/Users/damientully/.pyenv/versions/anaconda3-5.3.1/envs/pangolin/lib/python3.6/site-packages/scikit_learn-0.24.0rc1-py3.6-macosx-10.7-x86_64.egg/sklearn/__check_build/__init__.py", line 46, in <module>
    raise_build_error(e)
  File "/Users/damientully/.pyenv/versions/anaconda3-5.3.1/envs/pangolin/lib/python3.6/site-packages/scikit_learn-0.24.0rc1-py3.6-macosx-10.7-x86_64.egg/sklearn/__check_build/__init__.py", line 41, in raise_build_error
    %s""" % (e, local_dir, ''.join(dir_content).strip(), msg))
ImportError: dlopen(/Users/damientully/.pyenv/versions/anaconda3-5.3.1/envs/pangolin/lib/python3.6/site-packages/scikit_learn-0.24.0rc1-py3.6-macosx-10.7-x86_64.egg/sklearn/__check_build/_check_build.cpython-36m-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/damientully/.pyenv/versions/anaconda3-5.3.1/envs/pangolin/lib/python3.6/site-packages/scikit_learn-0.24.0rc1-py3.6-macosx-10.7-x86_64.egg/sklearn/__check_build/../.dylibs/libomp.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/damientully/.pyenv/versions/anaconda3-5.3.1/envs/pangolin/lib/python3.6/site-packages/scikit_learn-0.24.0rc1-py3.6-macosx-10.7-x86_64.egg/sklearn/__check_build/../.dylibs/libomp.dylib
___________________________________________________________________________
Contents of /Users/damientully/.pyenv/versions/anaconda3-5.3.1/envs/pangolin/lib/python3.6/site-packages/scikit_learn-0.24.0rc1-py3.6-macosx-10.7-x86_64.egg/sklearn/__check_build:
__init__.py               __pycache__               _check_build.cpython-36m-darwin.so
setup.py
___________________________________________________________________________
It seems that scikit-learn has not been built correctly.

If you have installed scikit-learn from source, please do not forget
to build the package before using it: run `python setup.py install` or
`make` in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.
[Thu Dec 10 17:59:55 2020]
Error in rule pangolearn:
    jobid: 2
    output: /var/folders/qf/xyw13rmn5_12v4d64rzh6lpc0000gn/T/tmp3gqzmz5f/lineage_report.pass_qc.csv
    shell:
        
        pangolearn.py --header-file /Users/damientully/.pyenv/versions/anaconda3-5.3.1/envs/pangolin/lib/python3.6/site-packages/pangoLEARN/data/decisionTreeHeaders_v1.joblib --model-file /Users/damientully/.pyenv/versions/anaconda3-5.3.1/envs/pangolin/lib/python3.6/site-packages/pangoLEARN/data/decisionTree_v1.joblib --reference-file /Users/damientully/.pyenv/versions/anaconda3-5.3.1/envs/pangolin/lib/python3.6/site-packages/pangolin/data/reference.fasta --fasta /var/folders/qf/xyw13rmn5_12v4d64rzh6lpc0000gn/T/tmp3gqzmz5f/post_qc_query.aligned.fasta -o /var/folders/qf/xyw13rmn5_12v4d64rzh6lpc0000gn/T/tmp3gqzmz5f/lineage_report.pass_qc.csv
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message
```

**Comment by damientully** [comment]
Hi @aineniamh ,

Fixed. Thanks.
D
