### ISSUE TITLE
Failure in datafunk_trim_and_pad due to fasta header too long

### ISSUE THREAD

**Issue by marcadella** [cov-lineages/pangolin#121]
It seems that older versions of pysam do not accept headers longer than 252 characters. But it looks like upgrading pysam to 0.16.0+ would solve the issue (see [here](https://github.com/pysam-developers/pysam/issues/447#issuecomment-734999015)).

Here is my log:
```
[E::sam_parse1] query name too long
[W::sam_read1] Parse error at line 5
Traceback (most recent call last):
  File "/miniconda/envs/pangolin/bin/datafunk", line 8, in <module>
    sys.exit(main())
  File "/miniconda/envs/pangolin/lib/python3.7/site-packages/datafunk/__main__.py", line 1051, in main
    args.func(args)
  File "/miniconda/envs/pangolin/lib/python3.7/site-packages/datafunk/subcommands/sam_2_fasta.py", line 71, in run
    trimend = trimend)
  File "/miniconda/envs/pangolin/lib/python3.7/site-packages/datafunk/sam_2_fasta.py", line 281, in sam_2_fasta
    one_querys_alignment_lines = [x for x in one_querys_alignment_lines if parse_sam_line(x)['SEQ'] != 'None']
  File "/miniconda/envs/pangolin/lib/python3.7/site-packages/datafunk/sam_2_fasta.py", line 281, in <listcomp>
    one_querys_alignment_lines = [x for x in one_querys_alignment_lines if parse_sam_line(x)['SEQ'] != 'None']
  File "pysam/libcalignmentfile.pyx", line 1852, in pysam.libcalignmentfile.AlignmentFile.__next__
OSError: truncated file
[Wed Jan 20 10:01:44 2021]
Error in rule datafunk_trim_and_pad:
    jobid: 9
    output: /tmp/tmpyjxhltqz/post_qc_query.aligned.fasta
    shell:

        datafunk sam_2_fasta           -s /tmp/tmpyjxhltqz/reference_mapped.sam           -r /miniconda/envs/pangolin/lib/python3.7/site-packages/pangolin-2.1.7-py3.7.egg/pangolin/data/reference.fasta           -o /tmp/tmpyjxhltqz/post_qc_query.aligned.fasta           -t [265:29674]           --pad           --log-inserts
```

**Comment by aineniamh** [comment]
Hi @marcadella, I've just updated the setup.py script to require `pysam>=0.16.0`, so the master now has this change. Hope this has resolved the issue, if not we can look further!
