### ISSUE TITLE
ModuleNotFoundError: No module named 'lineages'

### ISSUE THREAD

**Issue by BisonKok** [cov-lineages/pangolin#127]
Hi,
I receive the following error when triggering `pangolin -v`
```
Traceback (most recent call last):
  File "/opt/louis/devel/anaconda3/envs/pangolin/bin/pangolin", line 33, in <module>
    sys.exit(load_entry_point('pangolin==2.1.8', 'console_scripts', 'pangolin')())
  File "/opt/louis/devel/anaconda3/envs/pangolin/bin/pangolin", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/louis/devel/anaconda3/envs/pangolin/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 96, in load
    module = import_module(match.group('module'))
  File "/opt/louis/devel/anaconda3/envs/pangolin/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/louis/devel/anaconda3/envs/pangolin/lib/python3.7/site-packages/pangolin-2.1.8-py3.7.egg/pangolin/command.py", line 16, in <module>
    import lineages
ModuleNotFoundError: No module named 'lineages'
```

I don't seem to be able to find information on `lineages` module. What is it actually and how to I get it installed? Thanks in advance.

**Comment by aineniamh** [comment]
Hi, I recommend using the environment file and following the install instructions on the website (here: https://cov-lineages.org/pangolin.html), which involves use of conda. Information about the lineages repository is also found at the link there. If you can't use conda, the lineages repo can also be pip installed from the github repository here: https://github.com/cov-lineages/lineages.
