### ISSUE TITLE
ModuleNotFoundError: No module named 'snakemake'

### ISSUE THREAD

**Issue by pmenzel** [cov-lineages/pangolin#145]
Just in case anyone else encounters this issue:

After running
```
git clone https://github.com/cov-lineages/pangolin.git
conda env create -f environment.yml
conda activate pangolin
python setup.py install
```
I got this error when running `pangolin`:
```
Traceback (most recent call last):
  File "/opt/conda/miniconda3/bin/pangolin", line 33, in <module>
    sys.exit(load_entry_point('pangolin==2.3', 'console_scripts', 'pangolin')())
  File "/opt/conda/miniconda3/bin/pangolin", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/conda/miniconda3/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/opt/conda/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/miniconda3/lib/python3.8/site-packages/pangolin-2.3-py3.8.egg/pangolin/command.py", line 5, in <module>
    import snakemake
ModuleNotFoundError: No module named 'snakemake'
```
The solve it, it is enough to run
```
conda deactivate
conda activate pangolin
```
and `pangolin` works.

**Comment by idolawoye** [comment]
Hi @pmenzel, I am having the same issue as you and did `conda deactivate` and `conda activate pangolin` but it didn't resolve it. Any ideas @aineniamh ? Thanks
