### ISSUE TITLE
Install fail -- custom_logger.py no found

### ISSUE THREAD

**Issue by helixscript** [cov-lineages/pangolin#155]
Hi pangolin folks.

Our group has used your software sucessfully for some time.
We reinstalled the software today because the update flag was not available in our version.
pangolin crashes on start (below using miniconda3 after conda update -all).
Any help would certainly be appreciated !

Best,
John

(pangolin) everett@microb191:~/ext/pangolin$ pangolin -v
Traceback (most recent call last):
  File "/home/everett/miniconda3/envs/pangolin/bin/pangolin", line 33, in <module>
    sys.exit(load_entry_point('pangolin==2.2.3', 'console_scripts', 'pangolin')())
  File "/home/everett/miniconda3/envs/pangolin/bin/pangolin", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/everett/miniconda3/envs/pangolin/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 100, in load
    module = import_module(match.group('module'))
  File "/home/everett/miniconda3/envs/pangolin/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/everett/ext/pangolin/pangolin/command.py", line 19, in <module>
    import custom_logger as custom_logger
  File "/home/everett/miniconda3/envs/pangolin/bin/custom_logger.py", line 4, in <module>
    __import__('pkg_resources').run_script('pangolin==2.2.3', 'custom_logger.py')
  File "/home/everett/miniconda3/envs/pangolin/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/everett/miniconda3/envs/pangolin/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/custom_logger.py' not found in metadata at '/home/everett/ext/pangolin/pangolin.egg-info'

**Comment by aineniamh** [comment]
Hi, this looks like an installation error, if you try running
```
pip uninstall pangolin
```
and then
```
git pull
python setup.py install
```
while in the pangolin repository that should solve your issue.

**Comment by aineniamh** [comment]
Haven't heard back, so will assume the installation issue has been resolved! Closing the issue.
