### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by rakulase** [cov-lineages/pangolin#192]
hi guys 
I just updated the version to 2.4.2 and when I checked version or try to run lineage assignments the whole thing crashes. This seems to be similar to the issue reported previously. Not sure if this has anything to do with my local set up - but this has not happened before.

Traceback (most recent call last):
  File "/home/miniconda3/envs/pangolin/bin/pangolin", line 33, in <module>
    sys.exit(load_entry_point('pangolin==2.4.2', 'console_scripts', 'pangolin')())
  File "/home/miniconda3/envs/pangolin/bin/pangolin", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/miniconda3/envs/pangolin/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 96, in load
    module = import_module(match.group('module'))
  File "/home/miniconda3/envs/pangolin/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miniconda3/envs/pangolin/lib/python3.7/site-packages/pangolin/command.py", line 23, in <module>
    import custom_logger as custom_logger
  File "/home/miniconda3/envs/pangolin/bin/custom_logger.py", line 4, in <module>
    __import__('pkg_resources').run_script('pangolin==2.4.2', 'custom_logger.py')
  File "/home/miniconda3/envs/pangolin/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/miniconda3/envs/pangolin/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/custom_logger.py' not found in metadata at '/home/miniconda3/envs/pangolin/lib/python3.7/site-packages/pangolin-2.4.2.dist-info'

**Comment by rakulase** [comment]
I reinstalled after uninstalling the older versions and this seems to hav fixed the issue. This can be closed. Thank you.
