### ISSUE TITLE
which: no usher 

### ISSUE THREAD

**Issue by EricFournier3** [cov-lineages/pangolin#207]
Hi,

I got this error this morning after an update to version 3.0.2

which: no usher in */bin
Traceback (most recent call last):
  File "/data/Applications/Miniconda/miniconda3/envs/pangolin/bin/pangolin", line 8, in <module>
    sys.exit(main())
  File "/data/Applications/Miniconda/miniconda3/envs/pangolin/lib/python3.8/site-packages/pangolin/command.py", line 76, in main
    dependency_checks.check_dependencies()
  File "/data/Applications/Miniconda/miniconda3/envs/pangolin/lib/python3.8/site-packages/pangolin/utils/dependency_checks.py", line 52, in check_dependencies
    sys.stderr.write(cyan(f'Error: Missing dependencies.')+f'\n{dependencies}Please update your pangolin environment.\n')
NameError: name 'cyan' is not defined

Regards
Eric

**Comment by rmcolq** [comment]
The new major release requires an environment update to install new dependencies, including usher, constellations and scorpio. Please see https://cov-lineages.org/pangolin_docs/updating.html for how to update your environment

**Comment by aineniamh** [comment]
Thanks @EricFournier3, the cyan issue is fixed now in the master, but in general that release needed a full environment update as it was a major release, as Rachel linked to!
