### ISSUE TITLE
--update command with error with version 3.0.3

### ISSUE THREAD

**Issue by chienchi** [cov-lineages/pangolin#211]
Hi, 

I have install the latest version (v3.0.3) of pangolin today (May 28, 2021) and I tried to update again to see if there is any new updates. It shows following error.

Thank you.

```
pangolin --update 
pangolin 3.0.3 v3.0.3
pangolin already latest release (v3.0.3)
pangoLEARN 2021-05-27 2021-05-27
pangoLEARN already latest release (2021-05-27)
constellations 2021-04-09 v0.0.2
Traceback (most recent call last):
  File "/home/edge/edge_dev/thirdParty/Anaconda3/envs/pangolin/bin/pangolin", line 8, in <module>
    sys.exit(main())
  File "/home/edge/edge_dev/thirdParty/Anaconda3/envs/pangolin/lib/python3.8/site-packages/pangolin/command.py", line 83, in main
    update(__version__, pangoLEARN.__version__, constellations.__version__)
  File "/home/edge/edge_dev/thirdParty/Anaconda3/envs/pangolin/lib/python3.8/site-packages/pangolin/command.py", line 380, in update
    if version < latest_release:
  File "/home/edge/edge_dev/thirdParty/Anaconda3/envs/pangolin/lib/python3.8/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/home/edge/edge_dev/thirdParty/Anaconda3/envs/pangolin/lib/python3.8/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'int' and 'str'
```

**Comment by fmaguire** [comment]
This is related to a temporary issue ironing out version labelling in constellations but is fixed now (https://github.com/cov-lineages/constellations/issues/2)

If you manually update constellations with `pip install git+https://github.com/cov-lineages/constellations.git` then `pangolin --update` should work as expected.

**Comment by aineniamh** [comment]
Thanks @fmaguire! This issue is resolved with a full env update as described here: https://cov-lineages.org/pangolin_docs/updating.html
Usually wouldn't be needed for patches but we've had a couple of teething issues with the major changes in the pipeline pangolin 3.0 😅

**Comment by chienchi** [comment]
Thank you.
