### ISSUE TITLE
TypeError: can't pickle _thread.RLock objects

### ISSUE THREAD

**Issue by SethosII** [cov-lineages/pangolin#239]
I'm using a self compiled pangolin 3.0.5 and I get a similar error as in #223:

```
$ ml pangolin/3.0.5-foss-2018b-Python-3.6.6
$ pangolin rki_consensus.fasta                                                                                
All dependencies satisfied.
The query file is:/dev/shm/pangolin/rki_consensus.fasta                                                                   
** Sequence QC **                                 
Sequence name                                      Reason       Value                                               
                                  
... # omitted               
                       
                                                                                                                          
Number of sequences detected: 85                  
Total passing QC: 77                                                                                                
                       
Data files found:                                                                                                         
Trained model:  /mnt/software/easybuild/test/software/pangolin/3.0.5-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/pangoLEARN/data/decisionTree_v1.jobli
b
Header file:    /mnt/software/easybuild/test/software/pangolin/3.0.5-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/pangoLEARN/data/decisionTreeHeaders_v
1.joblib
Designated hash:        /mnt/software/easybuild/test/software/pangolin/3.0.5-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/pangoLEARN/data/lineages.hash
.csv
Traceback (most recent call last):
  File "/mnt/software/easybuild/test/software/snakemake/5.13.0-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/snakemake/__init__.py", line 488, in snakem
ake
    resources=resources,
  File "/mnt/software/easybuild/test/software/snakemake/5.13.0-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/snakemake/workflow.py", line 190, in __init
__
    config = copy.deepcopy(self.overwrite_config)
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 150, in deepcopy                                          
    y = copier(x, memo)                                                                                                                                       
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 240, in _deepcopy_dict                                    
    y[deepcopy(key, memo)] = deepcopy(value, memo)                                                                                                            
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 150, in deepcopy                                          
    y = copier(x, memo)                                                                                                                                       
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 215, in _deepcopy_list                                    
    append(deepcopy(a, memo))                                                                                                                                 
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 150, in deepcopy                                          
    y = copier(x, memo)                                                                                                                                       
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 247, in _deepcopy_method                                  
    return type(x)(x.__func__, deepcopy(x.__self__, memo))                                                                                                    
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 180, in deepcopy                                          
    y = _reconstruct(x, memo, *rv)                                                                                                                            
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 280, in _reconstruct                                      
    state = deepcopy(state, memo)                                                                                                                             
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 150, in deepcopy                                          
    y = copier(x, memo)                                                                                                                                       
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 240, in _deepcopy_dict                                    
    y[deepcopy(key, memo)] = deepcopy(value, memo)                                                                                                            
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 180, in deepcopy                                          
    y = _reconstruct(x, memo, *rv)                                                                                                                            
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)   
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)    
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))                                                                                                                                 
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)                                                                                                                            
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)                                                                                                                             
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)           
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 240, in _deepcopy_dict                                    
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/software/easybuild/18.04/software/Python/3.6.6-foss-2018b/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)                                                                                                                                          
TypeError: can't pickle _thread.RLock objects
```

Running the same fasta file with pangolin 2.4.2 with the same modules loaded works just fine:

```
$ ml pangolin/2.4.2-foss-2018b-Python-3.6.6
$ pangolin rki_consensus.fasta
All dependencies satisfied.
The query file is:/dev/shm/pangolin/rki_consensus.fasta
... # omitted
Looking in /mnt/software/easybuild/test/software/pangolin/2.4.2-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/pangoLEARN/data for data files...

Data files found
Trained model:  /mnt/software/easybuild/test/software/pangolin/2.4.2-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/pangoLEARN/data/decisionTree_v1.joblib
Header file:    /mnt/software/easybuild/test/software/pangolin/2.4.2-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/pangoLEARN/data/decisionTreeHeaders_v1.joblib
Lineages csv:   /mnt/software/easybuild/test/software/pangolin/2.4.2-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/pangoLEARN/data/lineages.metadata.csv
Job counts:
        count   jobs
        1       add_failed_seqs
        1       align_to_reference
        1       all
        1       overwrite
        1       pangolearn
        1       type_variants_b117
        1       type_variants_b1351
        1       type_variants_p1
        1       type_variants_p2
        1       type_variants_p3
        10
[M::mm_idx_gen::0.004*1.81] collected minimizers
[M::mm_idx_gen::0.005*1.61] sorted minimizers
[M::main::0.005*1.61] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.005*1.58] mid_occ = 100
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.005*1.56] distinct minimizers: 2952 (100.00% are singletons); average occurrences: 1.000; average spacing: 10.130
[M::worker_pipeline::1.579*0.80] mapped 82 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -a -x asm5 --sam-hit-only --secondary=no -t 1 /mnt/software/easybuild/test/software/pangolin/2.4.2-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/pangolin/data/reference.fasta /tmp/tmp286r4kni/query.post_qc.fasta
[M::main] Real time: 1.580 sec; CPU: 1.266 sec; Peak RSS: 0.020 GB
loading model 06/11/2021, 10:28:45
processing block of 82 sequences 06/11/2021, 10:28:48
complete 06/11/2021, 10:28:50
Job counts:
        count   jobs
        1       add_failed_seqs
        1
Job counts:
        count   jobs
        1       overwrite
        1
Output file written to: /dev/shm/pangolin/lineage_report.csv
```

Here is a list of the dependencies I used:
- Biopython 1.74
- gofasta 0.04
- minimap2 2.17
- pandas 1.0.1
- Pysam 0.16.0.1
- Python 3.6.6
- snakemake 5.13.0
- UShER 0.3.1 (only for pangolin 3.0.5)
- pangoLEARN 2021-06-05 (only for pangolin 3.0.5)
- pangoLEARN 2021-05-19 (only for pangolin 2.4.2, last working version for pangolin 2)
- scorpio master (only for pangolin 3.0.5, master because it doesn't need the unused dependencies, you should definitly consider to put this into a new release)
- constellations 0.0.4 (only for pangolin 3.0.5)
- amply 0.1.4
- PuLP 2.4
- threadpoolctl 2.1.0
- scikit-learn 0.23.1
- wheel 0.34.0

The dependencies used are the same (except for the new ones needed by version 3.0.5) so I think there is something wrong in pangolin. I tried to rebuild it but I still get the same error.

**Comment by aineniamh** [comment]
I wonder if a newer version of python will help? The environment file specifies python 3.7 or greater, but I see you're running python 3.6. Potentially try rebuilding the environment from scratch?

**Comment by SethosII** [comment]
Oh, I overlooked that. I rebuild pangolin and it's dependencies with Python 3.7.0 and it works now. Thanks!
