### ISSUE TITLE
--decompress-model => IndexError: list index out of range

### ISSUE THREAD

**Issue by tseemann** [cov-lineages/pangolin#291]
```
% pangolin --decompress-model
All dependencies satisfied.

Traceback (most recent call last):
  File "/home/tseemann/.conda/envs/pangolin/bin/pangolin", line 8, in <module>
    sys.exit(main())
  File "/home/tseemann/.conda/envs/pangolin/lib/python3.8/site-packages/pangolin/command.py", line 195, in main
    query = os.path.join(cwd, args.query[0])
IndexError: list index out of range
(covid) tseemann@eddie:EPI
```

Here are my versions
```
pangolin already latest release (v3.1.10)
pangolearn already latest release (2021-07-28)
constellations already latest release (v0.0.13)
scorpio already latest release (v0.3.12)
pango-designation already latest release (v1.2.56)

```

**Comment by aineniamh** [comment]
Hey @tseemann, I've just pushed a fix for that now! You may have been the first person to try using that feature! 😆
