### ISSUE TITLE
SyntaxError: future feature annotations is not defined

### ISSUE THREAD

**Issue by ala98412** [cov-lineages/pangolin#309]
I got this error message

Traceback (most recent call last):
  File "/usr/local/bin/pangolin", line 33, in <module>
    sys.exit(load_entry_point('pangolin==3.1.11', 'console_scripts', 'pangolin')())
  File "/usr/local/lib/python3.6/dist-packages/pangolin-3.1.11-py3.6.egg/pangolin/command.py", line 199, in main
    dependency_checks.check_dependencies()
  File "/usr/local/lib/python3.6/dist-packages/pangolin-3.1.11-py3.6.egg/pangolin/utils/dependency_checks.py", line 41, in check_dependencies
    check_module(module, missing)
  File "/usr/local/lib/python3.6/dist-packages/pangolin-3.1.11-py3.6.egg/pangolin/utils/dependency_checks.py", line 20, in check_module
    importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/pandas-1.3.2-py3.6-linux-x86_64.egg/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/usr/local/lib/python3.6/dist-packages/pandas-1.3.2-py3.6-linux-x86_64.egg/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/usr/local/lib/python3.6/dist-packages/pandas-1.3.2-py3.6-linux-x86_64.egg/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/usr/local/lib/python3.6/dist-packages/pandas-1.3.2-py3.6-linux-x86_64.egg/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/usr/local/lib/python3.6/dist-packages/pandas-1.3.2-py3.6-linux-x86_64.egg/pandas/util/_decorators.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

Versions: 
Python 3.8.0
Cython==3.0a1

Could anyone help to resolve this problem? Thanks a lot.

**Comment by aineniamh** [comment]
This looks like a pandas error.

if you try pip uninstalling pandas, and then updating the pangolin environment, or pip uninstalling pangolin and reinstall that may sort it out?

**Comment by ala98412** [comment]
Hi, aineniamh

I tried to uninstall pandas, and install pandas back, but the problem still exist.
But I notice another problem, 

File "/usr/local/lib/python3.6/dist-packages/pandas-1.3.2-py3.6-linux-x86_64.egg/pandas/util/_decorators.py", line 1

seems like pangolin use packages in folder python3.6.

Will this cause problem? And how can I fix it?

Thanks a lot.

**Comment by aineniamh** [comment]
Ah thats definitely the issue! May need to uninstall and reinstall the environment completely. To be safe maybe delete the pandas in python 3.6 too? Or just all python 3.6 packages if you don't use them anymore!

**Comment by aineniamh** [comment]
Ah, that may be the source of your issue then- the documentation explains how to install the conda environment with specific dependencies (https://cov-lineages.org/resources/pangolin/installation.html). 

I'd recommend going through the install steps at the link and that should sort your dependency issues out.

**Comment by ala98412** [comment]
Thanks a lot. I can use pangolin in conda env now. :)

**Comment by aineniamh** [comment]
Great! Glad it's working for you! 🎉
