### ISSUE TITLE
Panic error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by philiptzou** [cov-lineages/pangolin#434]
Hi, I found that Pangolin threw a panic error when a none-SARS-CoV-2 sequence was feed. The problematic sequence I tested is this one: https://www.ncbi.nlm.nih.gov/nuccore/AY910861.1?report=fasta

```
****
Pangolin running in usher mode.
****
Maximum ambiguity allowed is 0.3.
****
Query file:     /local/mhv.fasta
****
Data files found:
usher_pb:       /var/lang/lib/python3.8/site-packages/pangolin_data/data/lineageTree.pb
****
Job counts:
        count   jobs
        1       align_to_reference
        1       all
        1       cache_sequence_assign
        1       create_seq_hash
        1       get_constellations
        1       merged_info
        1       scorpio
        1       sequence_qc
        8
panic: runtime error: index out of range [0] with length 0

goroutine 20 [running]:
github.com/cov-ert/gofasta/pkg/sam.blockToFastaRecord(0xc0000bc480, 0xc000094180, 0xc000094240, 0x74cf, 0x101, 0x109, 0x73ea, 0x0)
        /Users/ben/programs/gofasta/pkg/sam/toma.go:76 +0x271
github.com/cov-ert/gofasta/pkg/sam.ToMultiAlign.func1(0xc0000bc480, 0xc000094180, 0xc000094240, 0x74cf, 0xc000090101, 0x109, 0x73ea, 0xc0000b83b0)
        /Users/ben/programs/gofasta/pkg/sam/toma.go:184 +0x7b
created by github.com/cov-ert/gofasta/pkg/sam.ToMultiAlign
        /Users/ben/programs/gofasta/pkg/sam/toma.go:183 +0x3b5
[Fri Apr 15 01:16:38 2022]
Error in rule align_to_reference:
    jobid: 1
    output: /tmp/tmpgxnbutbt/alignment.fasta
    log: /tmp/tmpgxnbutbt/logs/minimap2_sam.log (check log file(s) for error message)
    shell:

        awk '{ if ($0 !~ /^>/) { gsub("-", "",$0); } print $0; }' "/local/mhv.fasta" |         awk '{ { gsub(" ", "_",$0); } { gsub(",", "_",$0); } print $0; }'  |         minimap2 -a -x asm20 --sam-hit-only --secondary=no --score-N=0  -t  1 /var/lang/lib/python3.8/site-packages/pangolin/data/reference.fasta - -o /tmp/tmpgxnbutbt/mapped.sam &> /tmp/tmpgxnbutbt/logs/minimap2_sam.log
        gofasta sam toMultiAlign             -s /tmp/tmpgxnbutbt/mapped.sam             -t 1             --reference /var/lang/lib/python3.8/site-packages/pangolin/data/reference.fasta             --trimstart 265             --trimend 29674             --trim             --pad > '/tmp/tmpgxnbutbt/alignment.fasta'

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)


Exiting because a job execution failed. Look above for error message
```

I know this sequence shouldn't be assigned with any lineage. However, a panic error may prevent subsequent process running and we should avoid it.

**Comment by aineniamh** [comment]
I believe this is resolved now with the latest release, thanks for flagging!
