### ISSUE TITLE
Python Error after Updating Pangolin

### ISSUE THREAD

**Issue by steinbrl** [cov-lineages/pangolin#504]
Hey,

after conda update pangolin, it stopped working with the followed error massage:

----------------------------
Traceback (most recent call last):
  File "/home/lars/NGS/miniconda3/envs/pangolin/lib/python3.8/site-packages/snakemake/__init__.py", line 699, in snakemake
    success = workflow.execute(
  File "/home/lars/NGS/miniconda3/envs/pangolin/lib/python3.8/site-packages/snakemake/workflow.py", line 1039, in execute
    logger.run_info("\n".join(dag.stats()))
  File "/home/lars/NGS/miniconda3/envs/pangolin/lib/python3.8/site-packages/snakemake/dag.py", line 2159, in stats
    yield tabulate(rows, headers="keys")
  File "/home/lars/NGS/miniconda3/envs/pangolin/lib/python3.8/site-packages/tabulate/__init__.py", line 2048, in tabulate
    list_of_lists, headers = _normalize_tabular_data(
  File "/home/lars/NGS/miniconda3/envs/pangolin/lib/python3.8/site-packages/tabulate/__init__.py", line 1471, in _normalize_tabular_data
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/home/lars/NGS/miniconda3/envs/pangolin/lib/python3.8/site-packages/tabulate/__init__.py", line 1471, in <lambda>
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/home/lars/NGS/miniconda3/envs/pangolin/lib/python3.8/site-packages/tabulate/__init__.py", line 107, in _is_separating_line
    (len(row) >= 1 and row[0] == SEPARATING_LINE)
  File "/home/lars/NGS/miniconda3/envs/pangolin/lib/python3.8/site-packages/snakemake/rules.py", line 1127, in __eq__
    return self.name == other.name and self.output == other.output
AttributeError: 'str' object has no attribute 'name'
-----------------------------------

I also tried to make a new environment, with a fresh installation, it produces the same error. I really need pangolin for the productive work, the web application is not a replacement. I run Miniconda3 under Ubuntu16...

Best,

Lars

**Comment by steinbrl** [comment]
A reinstall from git-pangolin-master, with pip install fixed it. It is working again...

**Comment by AngieHinrichs** [comment]
Hi @steinbrl, glad you were able to get it working, and sorry about the inconvenience!  I think this is due to the version incompatibility between tabulate 0.9 and snakemake <=6.8.0 described in #313.  I think under some circumstances updating usher `--no-pin` can somehow lead to tabulate also being updated from 0.8 to 0.9 which causes the problem.  (Anecdotally I saw it happen with `conda update --no-pin usher` but not `mamba update --no-pin usher`, although all the conda environment machinations are still pretty much a black box to me so I have no idea if that would hold for anyone else's environment.)

In case anyone runs into the same error, a reinstall as Lars did is the surest way to fix it, but you can also try this:
```
conda install -y tabulate=0.8.10
```
(Substitute mamba for conda if you use mamba)


Meanwhile @aineniamh -- @abel-betraoui pointed out in #489 that snakemake [7.15.2](https://github.com/snakemake/snakemake/releases/tag/v7.15.2) fixed the problem with tabulate incompatibility, so unpinning snakemake and tabulate might prevent this problem in future versions?  (If it doesn't cause new ones... 🙄)

**Comment by aineniamh** [comment]
Going to close this as issue has been resovled!

**Comment by corneliusroemer** [comment]
@aineniamh I just ran into this issue myself. How did you resolves this? I don't think the workarounds outlined by @AngieHinrichs are a permanent fix, more a stop gap.

**Comment by corneliusroemer** [comment]
A simple `mamba update pangolin` didn't do, so I started fresh. I wrote down instructions that should work more reliably here: #513
