### ISSUE TITLE
new updated pangolin doesn't work

### ISSUE THREAD

**Issue by yl315504** [cov-lineages/pangolin#535]
I just updated pangolin and it doesn't work. A new directory ".snakemake" was generated.

<img width="282" alt="Capture1" src="https://github.com/cov-lineages/pangolin/assets/25533752/05ea1f31-1789-4098-a847-34b0ffc0ab39">

<img width="324" alt="Capture2" src="https://github.com/cov-lineages/pangolin/assets/25533752/4f880bef-7a96-4e28-98e4-2f4000b7e352">

Below is message in the output.txt file.
Traceback (most recent call last):
  File "/work/08270/yanliu74/ls6/MC/envs/CovidBashR.v.0.7/lib/python3.8/site-packages/snakemake/__init__.py", line 699, in snakemake
    success = workflow.execute(
  File "/work/08270/yanliu74/ls6/MC/envs/CovidBashR.v.0.7/lib/python3.8/site-packages/snakemake/workflow.py", line 1043, in execute
    logger.run_info("\n".join(dag.stats()))
  File "/work/08270/yanliu74/ls6/MC/envs/CovidBashR.v.0.7/lib/python3.8/site-packages/snakemake/dag.py", line 2176, in stats
    yield tabulate(rows, headers="keys")
  File "/work/08270/yanliu74/ls6/MC/envs/CovidBashR.v.0.7/lib/python3.8/site-packages/tabulate/__init__.py", line 2048, in tabulate
    list_of_lists, headers = _normalize_tabular_data(
  File "/work/08270/yanliu74/ls6/MC/envs/CovidBashR.v.0.7/lib/python3.8/site-packages/tabulate/__init__.py", line 1471, in _normalize_tabular_data
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/work/08270/yanliu74/ls6/MC/envs/CovidBashR.v.0.7/lib/python3.8/site-packages/tabulate/__init__.py", line 1471, in <lambda>
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/work/08270/yanliu74/ls6/MC/envs/CovidBashR.v.0.7/lib/python3.8/site-packages/tabulate/__init__.py", line 107, in _is_separating_line
    (len(row) >= 1 and row[0] == SEPARATING_LINE)
  File "/work/08270/yanliu74/ls6/MC/envs/CovidBashR.v.0.7/lib/python3.8/site-packages/snakemake/rules.py", line 1127, in __eq__
    return self.name == other.name and self.output == other.output
AttributeError: 'str' object has no attribute 'name'
[32m****
Pangolin running in usher mode.
****[0m
[32m
--no-temp: [0mall intermediate files will be written to /scratch/08270/yanliu74/UTSW_covid/Project_JAS_2023_12_06_COV212_13461_0/output

[32mMaximum ambiguity allowed is 0.5.
****[0m
[32mQuery file:	[0m/scratch/08270/yanliu74/UTSW_covid/Project_JAS_2023_12_06_COV212_13461_0/Project_JAS_2023_12_06_COV212_13461_0.trim.t0.5.ivar.fasta
[32m****
Data files found:[0m
usher_pb:	/work/08270/yanliu74/ls6/MC/envs/CovidBashR.v.0.7/lib/python3.8/site-packages/pangolin_data/data/lineageTree.pb
[32m****[0m

**Comment by aineniamh** [comment]
Hi @yl315504, googling your error message, it seems that this has been flagged before:
https://github.com/cov-lineages/pangolin/issues/504
https://github.com/cov-lineages/pangolin/issues/489

And is down to a snakemake/tabulate version incompatibility. 

How did you install/ update pangolin? Through bioconda or via git clone and an environment update?

**Comment by yl315504** [comment]
We update pangolin every week. We got this error after update this week.
conda update pangolin --yes

**Comment by aineniamh** [comment]
Hi @yl315504, I've just re-triggered all tests in pangolin github actions and the current version is passing tests with all the latest installs. 

I suspect some part of the install you have is out of date- I notice you're running quite an old python version.
My recommendation would be to create a new environment for pangolin with a newer python version or remove/ uninstall pangolin from your `CovidBashR.v.0.7` environment and re-install again from scratch. 

I would also recommend using mamba as it is faster than conda.

**Comment by corneliusroemer** [comment]
@aineniamh Since October, conda comes with the mamba solver so should no longer have the speed issues yay!
See: https://docs.conda.io/projects/conda/en/latest/release-notes.html#with-this-23-10-0-release-we-are-changing-the-default-solver-of-conda-to-conda-libmamba-solver
