### ISSUE TITLE
Error in rule scorpio: with pangolin 4.3

### ISSUE THREAD

**Issue by gadepallivs** [cov-lineages/pangolin#537]
I have been using Pangolin 4.3 for a while within a WDL workflow and everything was running successfully. Last week noted that the web version was annotating fasta sequence as BA.2 while the command line version I had is annotating the same as XDD. I updated Pangolin env from 4.3 to 4.3.1 , using the command `pangolin --update` and that broke the complete pipeline. 

Tried installing 4.3 back and went through the troubles of installing. Request if you can update the installation guidelines, with versions of conda / mamba, or Python required to successfully work with the Pangolin command line. As well as system requirements that it should work without fail. 

``` bash
# Our HPC uname , Linux x86_64
module load python  # loads Python 3.6.6 :: Anaconda custom (64-bit) 
conda -V   # The conda version on our HPC is conda 4.5.9

# The below command stuck at solving the environment for a long time and worked once. 
# In either event, it takes about 45 min or so to succeed or to fail.
time conda create -n pangolin -c bioconda -c conda-forge  pangolin=4.3 -y 

# Activate the pangolin env
source activate pangolin

# Check python version
(pangolin) bash-4.2$ python -V
Python 3.8.18

# Check conda version
(pangolin) bash-4.2$ conda -V
conda 4.5.9

# Check pangolin all versions
(pangolin) bash-4.2$ pangolin --all-versions
pangolin: 4.3
pangolin-data: 1.24
constellations: v0.1.12
scorpio: 0.3.19
usher 0.6.3
gofasta 1.2.1
minimap2 2.26-r1175
faToVcf: 448
```
After the above steps was able to get the pangolin 4.3 back. However, now I get a different error in the WDL workflow which has been working with this version without any issue. The only change that happened for the stable workflow is, re-installing pangolin 4.3 . The error I get is as follows, and not sure what it is referring to or how to fix it. Appreciate if you could give me some direction to solve this.

usage 

`pangolin --analysis-mode fast multi_fasta_file.fasta`

Error

```

Error in rule scorpio:
    

RuleException:
CalledProcessError in file /users/PAS1212/cvd8903/.conda/envs/pangolin/lib/python3.8/site-packages/pangolin/scripts/preprocessing.smk, line 92:
Command 'set -euo pipefail;  scorpio classify                      -i  



  File "/users/PAS1212/cvd8903/.conda/envs/pangolin/lib/python3.8/site-packages/pangolin/scripts/preprocessing.smk", line 92, in __rule_scorpio
  File "/users/PAS1212/cvd8903/.conda/envs/pangolin/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-02-10T222112.737690.snakemake.log

```

I cannot find the .snakemake.log and no hidden folder. Could not find the source of the error and reaching out if you can help on this.

Also,, I have tried installing using mama. It does resolve faster, but the issue is every time it downloads an older version of Pangolin ( v 1.1.4). Tried updating but never worked. Below are the steps I followed with mamaba.

``` bash
module load python
conda create -n pangolin
source activate pangolin
conda install -c conda-forge mamba
mamba install -c bioconda -c conda-forge -c defaults pangolin

# after installing mamba, the python version is downgraded inthe pangolin env

(pangolin) bash-4.2$ mamba --version
mamba 1.5.6
conda 23.11.0

(pangolin) bash-4.2$python -V
Python 3.12.1


```

**Comment by AngieHinrichs** [comment]
Sorry to hear about the troubles.  First, to prevent the log files from being automatically removed on exit, run pangolin with the `--no-temp` option.  (If you want to specify the directory instead of getting a randomly generated directory like tmpzj2_93ox then you can add `--tempdir /path/to/output/dir`.)

> When I use mamba, it pins Python ( 3.12), but downloads the old pangolin version 1.1.5, and does not update on the update call. Still trying to troubleshoot that.

I don't know why but I recently found that I needed to configure channels in this order:

  - conda-forge
  - bioconda
  - defaults

Otherwise there were unresolvable conflicts between dependencies of dependencies.

**Comment by gadepallivs** [comment]
The channels are configured in the same order. Tried `--no-temp` 
Now I can check scorpio.log file. This is what it shows, do you know what could be causing this ?

```
INFO: Found file /users/PAS1203/osu8903/.conda/envs/pangolin/lib/python3.8/site-packages/constellations/definitions/cXE.json for constellation Omicron (XE-like) containing 6 defining mutations
INFO: Rules {'default': {'min_alt': 3, 'max_ref': 0}}
Process SyncManager-1:
Traceback (most recent call last):
  File "/users/PAS1203/osu8903/.conda/envs/pangolin/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/users/PAS1203/osu8903/.conda/envs/pangolin/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/users/PAS1203/osu8903/.conda/envs/pangolin/lib/python3.8/multiprocessing/managers.py", line 608, in _run_server
    server = cls._Server(registry, address, authkey, serializer)
  File "/users/PAS1203/osu8903/.conda/envs/pangolin/lib/python3.8/multiprocessing/managers.py", line 154, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/users/PAS1203/osu8903/.conda/envs/pangolin/lib/python3.8/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/users/PAS1203/osu8903/.conda/envs/pangolin/lib/python3.8/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: AF_UNIX path too long
Traceback (most recent call last):
  File "/users/PAS1203/osu8903/.conda/envs/pangolin/bin/scorpio", line 10, in <module>
    sys.exit(main())
  File "/users/PAS1203/osu8903/.conda/envs/pangolin/lib/python3.8/site-packages/scorpio/__main__.py", line 272, in main
    args.func(args)
  File "/users/PAS1203/osu8903/.conda/envs/pangolin/lib/python3.8/site-packages/scorpio/subcommands/classify.py", line 7, in run
    classify_constellations(options.input,
  File "/users/PAS1203/osu8903/.conda/envs/pangolin/lib/python3.8/site-packages/scorpio/scripts/type_constellations.py", line 763, in classify_constellations
    manager = mp.Manager()
  File "/users/PAS1203/osu8903/.conda/envs/pangolin/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/users/PAS1203/osu8903/.conda/envs/pangolin/lib/python3.8/multiprocessing/managers.py", line 583, in start
    self._address = reader.recv()
  File "/users/PAS1203/osu8903/.conda/envs/pangolin/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/users/PAS1203/osu8903/.conda/envs/pangolin/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/users/PAS1203/osu8903/.conda/envs/pangolin/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError


```

**Comment by AngieHinrichs** [comment]
> OSError: AF_UNIX path too long

A quick google search indicates that having a long TMPDIR environment variable may cause that.  Is there a way for you to find out what TMPDIR is set to in the environment in which you run pangolin? (or to set it to something short?)

> CondaValueError: Malformed version string '~': invalid character(s)

How are you obtaining environment.yml?  I don't see a '-' character in it.  Instead, why not directly install pangolin (from the bioconda channel) like this:
```
conda create -n pangolin
conda activate pangolin
conda install pangolin
```

**Comment by gadepallivs** [comment]
I just copied the env.yml file from your repo to my directory on HPC. The default Python on our HPC is 3.6. So, I tried, direct installations with python, 3.7, 3.8 and 3.9, something like this.

```
conda create -n pangolin python=3.7
conda activate pangolin
conda install pangolin=4.3 # If I use 4.3.1, I get error saying not found in the channels

```
I shared the error I get in the WDL workflow when I load python=3.8 above. Contacted our HPC support if that OSX error wasn't there before. Pangolin is failing only in the WDL workflow, it's something we use almost daily, and now the workflow is broken. So, trying to fix it ASAP. Is there any other way I can setup pangolin env, without depending on coda ? If, so can you share the steps to follow the installation ?

**Comment by AngieHinrichs** [comment]
Just to make sure I understand, is this correct?:
* you have installed pangolin v4.3 successfully
* when you run pangolin on the command line it seems OK
* when you run pangolin in WDL, scorpio fails and the scorpio log file contains "OSError: AF_UNIX path too long"

If that is correct, then can you find out what the environment variable `TMPDIR` is set to in your WDL workflow?  For example is there a way to add "echo $TMPDIR" to your WDL workflow just before running pangolin?

**Comment by gadepallivs** [comment]
Yes - for all 3. Ok, will check that.
