### ISSUE TITLE
Missing joblib module (Ubuntu 18.04.4, pangolin v2.0.4)

### ISSUE THREAD

**Issue by ArtPoon** [cov-lineages/pangolin#89]
Run threw the following exception:
```console
Traceback (most recent call last):
  File "/home/art/miniconda3/envs/pangolin/bin/pangolearn.py", line 4, in <module>
    __import__('pkg_resources').run_script('pangolin==2.0.4', 'pangolearn.py')
  File "/home/art/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/art/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/home/art/miniconda3/envs/pangolin/lib/python3.6/site-packages/pangolin-2.0.4-py3.6.egg/EGG-INFO/scripts/pangolearn.py", line 10, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
```

I installed `joblib` manually from https://github.com/joblib/joblib (`pip3` is broken), and rerunning now - is this module a missing dependency?

**Comment by aineniamh** [comment]
Hi Art, sklearn (which we have as a dependancy) has joblib as a dependency so if sklean was pip installed it should have installed joblib too. 
I've just added joblib to the setup.py script as it's no harm to have it there, but if pip is broken that may be why joblib wasn't installed already.
